#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x nitrogen > /dev/null || nitrogen --restore &

pgrep -x polkit-gnome-au > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

pgrep -x picom > /dev/null || picom --experimental-backends &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^10' follow=off
